x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    image: nginx:1-alpine
    ports:
      - "1236:1236"
      - "8536:8536"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
    restart: unless-stopped
    depends_on:
      - pictrs
      - lemmy-ui
    logging: *default-logging

  lemmy:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    hostname: lemmy
    restart: unless-stopped
    environment:
      - RUST_LOG=warn
      - LEMMY_DISABLE_ACTIVITY_SENDING=true
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
      - ./plugins:/plugins:Z
    depends_on:
      - postgres
      - pictrs
    logging: *default-logging

  lemmy-ui:
    image: dessalines/lemmy-ui:nightly
    environment:
      - LEMMY_UI_BACKEND=lemmy:8536
      - LEMMY_UI_HTTPS=false
    depends_on:
      - lemmy
    restart: unless-stopped
    logging: *default-logging
    init: true

  pictrs:
    image: asonix/pictrs:0.5
    hostname: pictrs
    environment:
      - PICTRS__SERVER__API_KEY=CHANGE_ME_PICTRS_KEY
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt:Z
    restart: unless-stopped
    logging: *default-logging

  postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine
    hostname: postgres
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=chozi
      - POSTGRES_PASSWORD=CHANGE_ME_DB_PASSWORD
      - POSTGRES_DB=chozi
    volumes:
      - ./volumes/postgres:/var/lib/postgresql:Z
      - ./customPostgresql.conf:/etc/postgresql.conf:Z
    restart: unless-stopped
    logging: *default-logging
